# **Numpy and Pandas**

**Question no:1**

In [ ]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
matrix=arr.reshape(2,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Question no:2**

In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
print(a[5:15])

[ 6  7  8  9 10 11 12 13 14 15]


**Question no:3**

In [ ]:
arr=np.arange(1,21)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


10.5
10.5
5.766281297335398


**Question no:4**

In [2]:
import numpy as np
x=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
y=np.array([1,2,3,4])
result= x-y
print(result)


[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


**Question no:5**

In [6]:
data={"Name":["Arun","Geethu","Anand","Aswathi","Neethu","Sharad","Divya","Anjali","Rohith","Akshara"],"age":[40,38,36,33,34,37,35,25,27,26],"gender":["Male","Female","Male","Female","Female","Male","Female","Female","Male","Female"]}
print(data)
import pandas as pd
df= pd.DataFrame(data)
print(df)

{'Name': ['Arun', 'Geethu', 'Anand', 'Aswathi', 'Neethu', 'Sharad', 'Divya', 'Anjali', 'Rohith', 'Akshara'], 'age': [40, 38, 36, 33, 34, 37, 35, 25, 27, 26], 'gender': ['Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']}
      Name  age  gender
0     Arun   40    Male
1   Geethu   38  Female
2    Anand   36    Male
3  Aswathi   33  Female
4   Neethu   34  Female
5   Sharad   37    Male
6    Divya   35  Female
7   Anjali   25  Female
8   Rohith   27    Male
9  Akshara   26  Female


**Question no:5**
**sub 1**


In [7]:
df["Occupation"]=["Programmer","Manager","Analyst","Programmer","Manager","Analyst","Programmer","Manger","Analyst","Programmer"]
print(df)

      Name  age  gender  Occupation
0     Arun   40    Male  Programmer
1   Geethu   38  Female     Manager
2    Anand   36    Male     Analyst
3  Aswathi   33  Female  Programmer
4   Neethu   34  Female     Manager
5   Sharad   37    Male     Analyst
6    Divya   35  Female  Programmer
7   Anjali   25  Female      Manger
8   Rohith   27    Male     Analyst
9  Akshara   26  Female  Programmer


**Question no:5**
**sub 2**

In [8]:
print(df[df["age"]>=30])

      Name  age  gender  Occupation
0     Arun   40    Male  Programmer
1   Geethu   38  Female     Manager
2    Anand   36    Male     Analyst
3  Aswathi   33  Female  Programmer
4   Neethu   34  Female     Manager
5   Sharad   37    Male     Analyst
6    Divya   35  Female  Programmer


**Question no:5**
**Sub 3**

In [20]:
df.to_csv("people.csv",index=False)
df1=pd.read_csv("people.csv")
print(df1)

      Name  age  gender  Occupation
0     Arun   40    Male  Programmer
1   Geethu   38  Female     Manager
2    Anand   36    Male     Analyst
3  Aswathi   33  Female  Programmer
4   Neethu   34  Female     Manager
5   Sharad   37    Male     Analyst
6    Divya   35  Female  Programmer
7   Anjali   25  Female      Manger
8   Rohith   27    Male     Analyst
9  Akshara   26  Female  Programmer
